Fix bug - Creating a VideoLibraryViewModel instance with ViewModelProvider causes an exception
Exception: "java.lang.RuntimeException: Cannot create an instance of class com.example.mediaplayerapp.ui.video_library.VideoLibraryViewModel"

Solution: Change VideoLibraryViewModel to extends AndroidViewModel instead of ViewModel and create a new constructor

Reference: https://stackoverflow.com/questions/48605672/cannot-create-an-instance-of-viewmodel-class-unable-to-start-activity-component